In [4]:
import pandas as pd
import numpy as np

In [5]:
survey_results_public = pd.read_csv('survey_results_public.csv')
survey_results_schema = pd.read_csv('survey_results_schema.csv')

C:\Users\ggguc\AppData\Local\Temp\ipykernel_10764\2058332766.py:1: DtypeWarning: Columns (0: JobSatPoints_15_TEXT, 1: DatabaseHaveEntry, 2: DevEnvHaveEntry, 3: SOTagsHaveEntry, 4: SOTagsWant Entry, 5: OfficeStackWantEntry, 6: CommPlatformHaveEntr, 7: CommPlatformWantEntr, 8: SO_Actions_15_TEXT, 9: AIAgentOrchestration, 10: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  survey_results_public = pd.read_csv('survey_results_public.csv')

In [6]:
survey_results_public.head(5)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

Завдання 1. Підрахунок загальної кількості респондентів

In [7]:
count_respondents = survey_results_public.shape[0]
print(f'The number of respondents is: {count_respondents}')

The number of respondents is: 49191

Завдання 2. Аналіз повноти відповідей респондентів

In [8]:
question = set(survey_results_schema['qname'])

columns = list(question.intersection(survey_results_public.columns))
dropna_columns = survey_results_public.dropna(subset = columns).shape[0]
print(f'The number of respondents that answered all questions is: {dropna_columns}')

The number of respondents that answered all questions is: 0

Завдання 3. Статистичний аналіз досвіду респондентів

In [9]:
workexp = survey_results_public['WorkExp'].agg(['mean',
                                                'median',
                                                lambda x: x.mode().iloc[0]])
workexp.head()

mean        13.367403
median      10.000000
<lambda>    10.000000
Name: WorkExp, dtype: float64

Задание 4. Анализ удаленной работы

In [10]:
workr_count = survey_results_public[survey_results_public['RemoteWork'] == 'Remote'].shape[0]
print(f'RemoteWork : {workr_count}')

RemoteWork : 10931

Задание 5. Определение популярности Python

In [11]:
languages_columns = [col for col in survey_results_public.columns if 'Language' in col]
print(languages_columns)

['LanguageChoice', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry', 'LanguagesWantEntry']

In [20]:
python_respondents = survey_results_public[
    survey_results_public['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)
]['ResponseId'].nunique()
total_respondents = survey_results_public['ResponseId'].nunique()
percent = python_respondents / total_respondents * 100
print(f"Percentage of respondents who want to work with Python: {percent:.2f}%")

Percentage of respondents who want to work with Python: 37.54%

Задание 6. Анализ путей обучения программированию

In [13]:
languages_columns = [col for col in survey_results_public.columns if 'Learn' in col]
online_courses_count = survey_results_public[survey_results_public['LearnCode'].str.contains('Online Courses or Certification', na=False)].shape[0]
print(f'Online Courses or Certification : {online_courses_count}')

Online Courses or Certification : 10973

Задание 7. Географический анализ компенсации Python-разработчиков

In [21]:
convertedCompYearly_columns = [col for col in survey_results_public.columns if 'ConvertedCompYearly' in col]
country_columns = [col for col in survey_results_public.columns if  'country' in col.lower()]

converted_dropna = survey_results_public.dropna(subset='ConvertedCompYearly')
avg_mean_country = converted_dropna[
    converted_dropna['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)
    ].groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median']).sort_values(by='median', ascending=False)
print(avg_mean_country)

                                   mean        median
Country
Oman                      390135.000000  390135.00000
Andorra                   226103.500000  226103.50000
Switzerland               142276.399233  122443.00000
United States of America  154740.648944  120000.00000
Luxembourg                111738.761970  103087.26995
...                                 ...           ...
Guinea                      2773.000000    2773.00000
Swaziland                   2312.000000    2312.00000
Burundi                     1697.000000    1697.00000
Botswana                    1277.000000    1277.00000
Antigua and Barbuda            1.000000       1.00000

[167 rows x 2 columns]

Задание 8. Анализ образования наиболее оплачиваемых специалистов

In [15]:
survey_results_public['EdLevel'] = survey_results_public['EdLevel'].fillna('Unknown')
sorted_converted = survey_results_public.sort_values(by='ConvertedCompYearly', ascending=False)
sorted_converted[['ResponseId', 'EdLevel', 'ConvertedCompYearly']].head(5)

,ResponseId,EdLevel,ConvertedCompYearly
34267,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
28700,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
43143,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
35353,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
45971,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0

Завдання 9. Аналіз популярності Python по віковим категоріям

In [16]:
age = set(survey_results_public['Age'])
print(age)

{'25-34 years old', '35-44 years old', '55-64 years old', '65 years or older', '18-24 years old', '45-54 years old', 'Prefer not to say'}

In [17]:
puthon_respondet1 = survey_results_public[survey_results_public['LanguageHaveWorkedWith'].str.contains('Python', na=False)]
age_python = puthon_respondet1.groupby('Age').size()
age_count_respondents = survey_results_public.groupby('Age').size()
percent_age_python = age_python / age_count_respondents * 100
print(percent_age_python)

Age
18-24 years old      40.000000
25-34 years old      36.939282
35-44 years old      36.719281
45-54 years old      38.629482
55-64 years old      37.242955
65 years or older    31.634820
Prefer not to say    31.216931
dtype: float64

Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [18]:
indastry_columns = [col for col in survey_results_public.columns if 'Industry' in col]
print(indastry_columns)

['Industry']

In [19]:
survey_results_public['Industry'] = survey_results_public['Industry'].fillna('Unknown')
sort_remoute = survey_results_public[survey_results_public['RemoteWork'] == 'Remote']
quantile75_ind = sort_remoute[
    sort_remoute['ConvertedCompYearly'] >= sort_remoute['ConvertedCompYearly'].quantile(0.75)
].groupby('Industry')['ResponseId'].count().sort_values(ascending=False)

print(quantile75_ind)

Industry
Software Development                          1315
Fintech                                        212
Healthcare                                     202
Other:                                         199
Internet, Telecomm or Information Services     152
Banking/Financial Services                      97
Government                                      89
Media & Advertising Services                    81
Retail and Consumer Services                    74
Transportation, or Supply Chain                 67
Computer Systems Design and Services            64
Energy                                          52
Insurance                                       50
Manufacturing                                   40
Higher Education                                39
Unknown                                          1
Name: ResponseId, dtype: int64